name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    services:
      backend:
        image: node:20
        ports: ['4000:4000']
        options: --health-cmd "curl -f http://localhost:4000/api/health || exit 1" --health-interval 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build frontend
        run: npm run build
      - name: Build backend
        run: docker build -f Dockerfile.backend .